<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "femanagerextended"
 *
 * Auto generated by Extension Builder 2013-06-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'femanagerextended',
    'description' => 'Extend fe_users and femanager with new fields ',
    'category' => 'plugin',
    'author' => 'Steven Nkeneng',
    'author_email' => 'nkeneng.junior@gmail.com',
    'author_company' => 'AleksundShantu',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.2.0',
    'constraints' => [
        'depends' => [
            'extbase' => '7.6.0-8.99.99',
            'fluid' => '7.6.0-8.99.99',
            'typo3' => '7.6.0-10.99.99',
            'femanager' => '2.0.0-2.99.99'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
